Add Alert for Leptos #62
RustForWeb/shadcn-ui pull request #196
Opened 2024-12-09 21:49 UTC by israelsilvabarbara

Added Alert feature to Leptos and also added examples in book-example.

2024-12-12 14:46 UTC, DanielleHuisman commented
Could you please resolve the merge conflicts? I will review the PR this weekend.

2024-12-15 20:07 UTC, DanielleHuisman requested changes
Thank you for contributing! The component is coming along nicely.

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/default/alert.rs
> +            <Route path=path!("/class") view=alert_class::AlertClass />
These examples don't exist for shadcn/ui's alert. The book only ports existing shadcn/ui examples.

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/default.rs
>  mod card;
```suggestion
#[cfg(feature = "alert")]
mod alert;
#[cfg(feature = "button")]
mod button;
#[cfg(feature = "card")]
mod card;
```

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/default.rs
> +        #[cfg(feature = "alert")]
Please keep this list sorted alphabetically.

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/new_york.rs
>  mod card;
```suggestion
#[cfg(feature = "alert")]
mod alert;
#[cfg(feature = "button")]
mod button;
#[cfg(feature = "card")]
mod card;
```

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/new_york.rs
> +        #[cfg(feature = "alert")]
Please keep this list sorted alphabetically.

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/default/components/ui.rs
>  pub use shadcn_ui_leptos_card::default as card;
```suggestion
#[cfg(feature = "alert")]
pub use shadcn_ui_leptos_alert::default as alert;
#[cfg(any(feature = "button", feature = "card"))]
pub use shadcn_ui_leptos_button::default as button;
#[cfg(feature = "card")]
pub use shadcn_ui_leptos_card::default as card;
```

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/src/new_york/components/ui.rs
>  pub use shadcn_ui_leptos_card::new_york as card;
```suggestion
#[cfg(feature = "alert")]
pub use shadcn_ui_leptos_alert::new_york as alert;
#[cfg(any(feature = "button", feature = "card"))]
pub use shadcn_ui_leptos_button::new_york as button;
#[cfg(feature = "card")]
pub use shadcn_ui_leptos_card::new_york as card;
```

2024-12-15 20:07 UTC, DanielleHuisman commented on book-examples/leptos/Cargo.toml
> +]
Please keep this sorted alphabetically.

When using icons in examples, the optional dependency needs to be enabled here, see the Yew book examples.

2024-12-17 16:40 UTC, israelsilvabarbara commented
To make it easier to review, I have implemented the requested changes in separate commits.

2024-12-23 16:25 UTC, DanielleHuisman approved these changes

2024-12-23 16:39 UTC, merged